### ISSUE TITLE
Vue3 引入不了

### ISSUE THREAD

**Issue by Harris-H** [941477276/vue3-country-intl#11]
![image](https://github.com/941477276/vue3-country-intl/assets/57698783/bebad961-109a-444b-b41d-fdd29cd4b0c2)

如上图所示

**Comment by 941477276** [comment]
这个是由于`vue3-country-intl`没有定义`.d.ts`类型声明文件导致的，你在`import Vue3CountryIntl from 'vue3-country-intl'`语句上面加句注释`// @ts-ignore`试试，或者在你的项目`src`目录添加一个`vue.d.ts`文件，文件内容里添加`declare module 'vue3-country-intl';`
