### ISSUE TITLE
如何放到弹窗里展示？默认下拉框在body!

### ISSUE THREAD

**Issue by Eacolt** [941477276/vue3-country-intl#12]
如何放到弹窗里展示？默认下拉框在body!我使用的vue3 + antdV，无法在Modal弹窗里打开下拉框，schema是input，被遮挡了

**Comment by 941477276** [comment]
能否截2张图看下，1效果图，2dom图

**Comment by 941477276** [comment]
问题已解决，请更新版本至`2.0.4`
