### ISSUE TITLE
国旗Icon不对

### ISSUE THREAD

**Issue by ooooshino** [941477276/vue3-country-intl#13]
安装、注册组件，都是按照这个文档走的[vue3-country-intl](https://github.com/941477276/vue3-country-intl)

虽然正确展示了，控制台也没报错，但是看到国旗和国家不对应

连续搜了几个，国旗都是错乱的

![f04e8da4e99cb9d63b2a12968ff5b1ed.png](https://i.mji.rip/2024/05/08/f04e8da4e99cb9d63b2a12968ff5b1ed.png)

![d4662b61e32a5962caf73b33b06fc5ba.png](https://i.mji.rip/2024/05/08/d4662b61e32a5962caf73b33b06fc5ba.png)

各版本如下：

```json
{
    "vue": "^3.3.4",
    "vue3-country-intl": "^2.0.3",
    "vite": "^4.4.5"
}
```

```json
{
    "macos": "13.5 (22G74)",
    "vscode": "Version: 1.88.1"
}
```

导入注册main.js：

```js
import VueCountryIntl from 'vue3-country-intl';
import 'vue3-country-intl/lib/vue3-country-intl.css'

createApp(App)
  .component(VueCountryIntl.name, VueCountryIntl)
  .mount('#app')
```

使用代码是文档里的popover模式 

```vue
 <Vue3CountryIntl
              schema="popover"
              elId="my_reference"
              v-model="schemaPopoverData.default"
              v-model:visible="schemaPopoverData.visible"
            >
              <button type="button" @click="schemaPopoverData.visible = true">
                选择手机区号
              </button>
</Vue3CountryIntl>
```

**Comment by 941477276** [comment]
可以贴下代码吗？demo里面的都是正确的呀

**Comment by ooooshino** [comment]
> 可以贴下代码吗？demo里面的都是正确的呀

更新Issues了，你看一下还需要什么

**Comment by 941477276** [comment]
我用你的示例代码跑了一下，没有出现你说的问题呀
![image](https://github.com/941477276/vue3-country-intl/assets/20528541/cd3a74f4-bfed-4e29-95c9-223bd9e42277)
![image](https://github.com/941477276/vue3-country-intl/assets/20528541/da180e04-6f5f-4569-a6b8-6b0a1f000691)
![image](https://github.com/941477276/vue3-country-intl/assets/20528541/bfb98e32-0a91-4c17-a962-44ccc20b1018)

运行结果
![image](https://github.com/941477276/vue3-country-intl/assets/20528541/062d3c28-934f-4d6f-bc0e-55bd0a6fd551)
![image](https://github.com/941477276/vue3-country-intl/assets/20528541/0350fd37-b5ca-414c-a51b-8bf1956505f2)

能否远程看下？地址栏有我QQ号

**Comment by hsk-story** [comment]
@941477276 这个似乎和浏览器版本有关系，我这边也遇到了，可以把国旗展示作为配置项隐藏掉吗

**Comment by 941477276** [comment]
> @941477276 这个似乎和浏览器版本有关系，我这边也遇到了，可以把国旗展示作为配置项隐藏掉吗

![image](https://github.com/941477276/vue3-country-intl/assets/20528541/c268c0f8-1b03-4694-944a-524f81331a26)
showLabelImg设置为false即可，你用的是什么浏览器？哪个版本？

**Comment by hsk-story** [comment]
找到问题了, 因为装了[postcss-px-to-viewport](https://github.com/evrone/postcss-px-to-viewport), 插件直接将所有的px都转成vw了, 导致iti-flag类下的background-position偏移量计算有问题. 
直接把iti-flag类名加到postcss-px-to-viewport的selectorBlackList黑名单配置上就能解决
