### ISSUE TITLE
关于台湾的简繁体

### ISSUE THREAD

**Issue by yllhwa** [941477276/vue3-country-intl#14]
为什么台湾为“中国台灣”而不是“中国台湾”？

**Comment by 941477276** [comment]
用“中国台灣”没问题，台湾那边是用繁体字

**Comment by yllhwa** [comment]
> 用“中国台灣”没问题，台湾那边是用繁体字

这样的话直接输入台湾就搜索不出来

**Comment by 941477276** [comment]
感谢你提的问题，该问题已在`2.0.6`版本修复，请更新版本至`2.0.6`
