### ISSUE TITLE
鼠标拖拽弹窗的滑动条，窗口会立刻消失

### ISSUE THREAD

**Issue by zzephyra** [941477276/vue3-country-intl#16]
https://github.com/user-attachments/assets/dbd136f9-e0f0-4a95-9aa4-b6488234f43d

**Comment by 941477276** [comment]
你用的什么浏览器？哪个版本？

**Comment by zzephyra** [comment]
![1722854498438](https://github.com/user-attachments/assets/974c7206-a417-4014-9146-bda6408c5fd4)

**Comment by zzephyra** [comment]
还有一个问题，组件似乎不能自定义选择后所展示的信息？

**Comment by 941477276** [comment]
我刚更新了谷歌浏览器的版本，没有复现你说的问题。你是在我的在线demo上操作的吗？
![image](https://github.com/user-attachments/assets/523e08c1-a329-4bd0-8e70-4ca8e568dc09)

**Comment by 941477276** [comment]
> 还有一个问题，组件似乎不能自定义选择后所展示的信息？

是的，之前没有这个需求，你想怎么自定义显示？可以把你的设计稿贴出来看下

**Comment by zzephyra** [comment]
> > 还有一个问题，组件似乎不能自定义选择后所展示的信息？
> 
> 是的，之前没有这个需求，你想怎么自定义显示？可以把你的设计稿贴出来看下

使用的时候部分国家名字过长，所以我想选择后，在input框内只显示 国旗+区号 的形式

**Comment by 941477276** [comment]
> > > 还有一个问题，组件似乎不能自定义选择后所展示的信息？
> > 
> > 
> > 是的，之前没有这个需求，你想怎么自定义显示？可以把你的设计稿贴出来看下
> 
> 使用的时候部分国家名字过长，所以我想选择后，在input框内只显示 国旗+区号 的形式

你这个需求我实现了，增加了`customInputLabel`插槽，需更新版本至`2.0.5`

**Comment by zzephyra** [comment]
> > > > 还有一个问题，组件似乎不能自定义选择后所展示的信息？
> > > 
> > > 
> > > 是的，之前没有这个需求，你想怎么自定义显示？可以把你的设计稿贴出来看下
> > 
> > 
> > 使用的时候部分国家名字过长，所以我想选择后，在input框内只显示 国旗+区号 的形式
> 
> 你这个需求我实现了，增加了`customInputLabel`插槽，需更新版本至`2.0.5`

非常感谢你的支持，谢谢！
