### ISSUE TITLE
选择地区区号时，默认绑定的值只能是区号吗？不能用其他值绑定吗？

### ISSUE THREAD

**Issue by yspwf** [941477276/vue3-country-intl#18]
区号作为v-model值绑定有bug啊，多个区域使用相同的区号时会默认使用第一个啊

**Comment by 941477276** [comment]
可以提供个复现的代码片段吗？

**Comment by yspwf** [comment]
这是个业务问题：具体描述如下
背景：通过组建选择国家对应的区号，type="phone"的模式（Australia，Christmas Island， Cocos (Keeling) Islands 三个国家的区号代码都是61）
1. 通过组建选择区号61
2. 保存到数据库
3. 页面再次展示回写61展示了错误的国家，事实上一直都是第一个国家

**Comment by 941477276** [comment]
这种情况是存在的，解决办法：需要给组件传递`iso2`属性，即国籍编码
1、在组件的`change`事件里获取到国家信息，里面会返回`iso2`
2、将`iso2`保存到数据库中
3、回填`iso2`属性给组件
