### ISSUE TITLE
项目报错

### ISSUE THREAD

**Issue by chenxin9482** [941477276/vue3-country-intl#2]
![image](https://user-images.githubusercontent.com/65519955/153582387-cdf0a39d-2cd1-4379-a5bb-9977d0bb6faf.png)

    "vite": "^2.4.4",
    "vue": "^3.1.5",
    "vue3-country-intl": "^1.0.4",

**Comment by chenxin9482** [comment]
这是我的调用方式
```html
<template>
  <Vue3CountryIntl v-model="state.userInfo.phoneCode" />
</template>
```
```js
<script>
import Vue3CountryIntl from 'vue3-country-intl'
import 'vue3-country-intl/lib/vue3-country-intl.css'
export default {
  components: {  Vue3CountryIntl },
}
</script>
```

**Comment by 941477276** [comment]
将vue3升级到最新版本试下，`3.2.30`

**Comment by chenxin9482** [comment]
还是报错

**Comment by 941477276** [comment]
把`node_modules`删掉再重装试下，出现这个问题的就是引入了多次`vue`，我之前也遇到过，我打包后的代码并不包含`vue`本身

**Comment by chenxin9482** [comment]
还是这样 12个报错 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'isCE')

**Comment by chenxin9482** [comment]
怎么处理可以不包含vue？

**Comment by 941477276** [comment]
你是打包还是本地调试？

**Comment by chenxin9482** [comment]
本地

**Comment by 941477276** [comment]
那不应该呀，你建个新项目试下，只引入我的这个插件

**Comment by chenxin9482** [comment]
还真没报错，可是这样我怎么排查呢？还请大佬教教

**Comment by 941477276** [comment]
你看下你有没有引入其他的组件，查查其他组件中是否将`vue`本身打包进去了，或者看下你自己的代码是否即有使用`import`形式导入`vue`，然后还有`<script>`标签形式引入`vue`

**Comment by chenxin9482** [comment]
呃 不知道怎么看其他组件中是否将`vue`本身打包进去了 第二种情况是没有的

**Comment by 941477276** [comment]
查找`Vue`关键字，看有没有定义`Vue`的地方

**Comment by chenxin9482** [comment]
没找到 可以加你微信帮我排查下么 会给你报酬的

**Comment by 941477276** [comment]
地址栏上有我QQ

**Comment by chenxin9482** [comment]
添加了

**Comment by magina000** [comment]
> 地址栏上有我QQ

现在有解决吗，我也出现一样的问题

**Comment by 941477276** [comment]
还没有，不知道为什么在你们一用就 会出现这个问题，我本地引用打包后的代码都不会出现这个问题，方便的话加QQ详聊下

**Comment by 941477276** [comment]
问题已解决，更新至`1.0.8`版本即可 @magina000 @chenxin9482
