### ISSUE TITLE
项目报错

### ISSUE THREAD

**Issue by yuyiqun** [941477276/vue3-country-intl#3]
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'nodeName')

**Comment by yuyiqun** [comment]
![image](https://user-images.githubusercontent.com/65887472/191246603-df589cb2-c2c2-46bd-bb16-75d81aad4dd2.png)

**Comment by yuyiqun** [comment]
点击输入框的时候报错

**Comment by 941477276** [comment]
请发一个复现问题的demo到我的邮箱（941477276@qq.com）

**Comment by 941477276** [comment]
更新到`1.0.14`试试
