### ISSUE TITLE
下拉框选择时切换点击无反应

### ISSUE THREAD

**Issue by yml-222** [941477276/vue3-country-intl#4]
下拉框选择时切换点击无反应，作者给的demo 也会有这种情况

https://user-images.githubusercontent.com/65451783/197684151-e8a5a83d-921f-4dcc-b779-5a44194e5654.mp4

**Comment by 941477276** [comment]
你绑定了`v-model`吗？

**Comment by 941477276** [comment]
> 下拉框选择时切换点击无反应，作者给的demo 也会有这种情况
> 
>  bandicam.2022-10-25.12-39-18-899.mp4

把你的代码贴出来看下

**Comment by yml-222** [comment]
> 你绑定了`v-model`吗？

绑定了，代码我当时用了有问题就删除了

**Comment by yml-222** [comment]
https://user-images.githubusercontent.com/65451783/201612500-292daa31-7f64-4219-b9d4-a83683a3071c.mp4

这个 作者给的demo，可以自己多试几次，点击了没有反应

**Comment by 941477276** [comment]
你用的什么浏览器？感觉有点像那个自动填充导致的

**Comment by yml-222** [comment]
> 你用的什么浏览器？感觉有点像那个自动填充导致的

用的谷歌浏览器

**Comment by 941477276** [comment]
> > 你用的什么浏览器？感觉有点像那个自动填充导致的
> 
> 用的谷歌浏览器

你用“无痕模式”访问看看

**Comment by 941477276** [comment]
代码更新了，升级到`1.0.15`试试
