### ISSUE TITLE
search="true"

### ISSUE THREAD

**Issue by news00** [941477276/vue3-country-intl#5]
搜索之后再选择，会出现选不中要选择的项，怀疑是事件委托的问题

**Comment by 941477276** [comment]
可以录个屏看下吗？及贴下你的代码

**Comment by news00** [comment]
https://user-images.githubusercontent.com/25659337/202097171-5cb1c06e-8f76-45f0-970c-76d1665671b7.mp4

**Comment by news00** [comment]
不搜索，直接选，是很少出现这个问题的

**Comment by news00** [comment]
<Vue3CountryIntl
        type="country"
        v-model="code"
        :useChinese="lang === 'zhCn'"
        :showAreaCode="true"
        :showSelectedText="false"
        :searchAble="true"
        @onChange="selectHandle"
        :placeholder="$t('el.select.placeholder')"
      />
      代码就是这样的

**Comment by 941477276** [comment]
代码更新了，升级到`1.0.15`试试

**Comment by news00** [comment]
好像可以了，我测试一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "941477276/vue3-country-intl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月17日(星期四) 上午9:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [941477276/vue3-country-intl] search="true" (Issue #5)





 
代码更新了，升级到1.0.15试试
