### ISSUE TITLE
默认选择区号问题

### ISSUE THREAD

**Issue by shallow-time** [941477276/vue3-country-intl#7]
scheme = input，type = phone,设置默认iso2为'us', 默认区号为‘1’，期望实现效果默认选择的是美国区号，实际却是不显示。

代码：
```
 <template> 
  <div>
       <Vue3CountryIntl :iso2="iso2"  type="phone" v-model="area_code" @onChange="handleChange"></Vue3CountryIntl>
  </div>
 </template>

 <script lang="ts" setup>
 import {ref} from 'vue';
 const iso2  = ref('us') // 期望默认区号为美国
 const area_code = ref('1')
 const handleChange = (options:any) =>{
    iso2.value = options.value
 }
</script>
```

效果显示：未成功显示期望的默认区号
![image](https://user-images.githubusercontent.com/66305157/210918518-3cc67368-000c-4dbf-991e-e142986c3d8a.png)

**Comment by 941477276** [comment]
升级到`1.0.16`版本可解决该问题
![image](https://user-images.githubusercontent.com/20528541/210986210-4b5b2991-203f-4d80-abc9-4a0448ddc62c.png)
![image](https://user-images.githubusercontent.com/20528541/210986421-1fad45f5-466d-4559-913b-799e8de526f0.png)
![image](https://user-images.githubusercontent.com/20528541/210986564-aa660170-b87f-492d-ab71-42996608da11.png)

**Comment by shallow-time** [comment]
> 升级到`1.0.16`版本可解决该问题 ![image](https://user-images.githubusercontent.com/20528541/210986210-4b5b2991-203f-4d80-abc9-4a0448ddc62c.png) ![image](https://user-images.githubusercontent.com/20528541/210986421-1fad45f5-466d-4559-913b-799e8de526f0.png) ![image](https://user-images.githubusercontent.com/20528541/210986564-aa660170-b87f-492d-ab71-42996608da11.png)

> vue: 3.2.36 版本，vue3-country-intl: 1.0.16 版本。依旧存在设置默认区号为美国，不显示问题，看下你这边vue版本是多少，确认下是不是vue版本导致的。
![image](https://user-images.githubusercontent.com/66305157/211231169-c4c9e640-d96f-4063-aa0d-68a0d0437719.png)
![image](https://user-images.githubusercontent.com/66305157/211231187-2e748377-7289-4c7a-be23-d28d65f63ace.png)
![image](https://user-images.githubusercontent.com/66305157/211231202-babc7f11-dd27-45ce-91f7-b825fec307d9.png)

**Comment by 941477276** [comment]
我用`3.2.36`版本的`vue`也是可以的
![image](https://user-images.githubusercontent.com/20528541/211259398-42e17aaa-4297-4f40-9f98-5d5a94728c26.png)
![image](https://user-images.githubusercontent.com/20528541/211259426-48bb38ac-077c-4b2f-aad5-30db37dabc48.png)
![image](https://user-images.githubusercontent.com/20528541/211259450-cfc4a8a6-c65a-4c61-813e-91810ccbefad.png)
![image](https://user-images.githubusercontent.com/20528541/211259466-ed01851a-5d08-4240-bd95-532a4bfb8b3d.png)
你新创建一个`vue3`项目，在新项目里使用`vue3-country-intl`组件看有没有效果
