### ISSUE TITLE
区号显示问题

### ISSUE THREAD

**Issue by shallow-time** [941477276/vue3-country-intl#8]
` 
<template>
    <Vue3CountryIntl :iso2="iso2" @onChange="onCountryChange" schema="input" type="phone" v-model="detail.area_code"></Vue3CountryIntl>
</template>
<script lang="ts" setup>
  import {ref,reactive, } from 'vue';
   const detail = reactive({
     area_code:"1"
})
  let iso2 = ref('us')
  const onCountryChange = (option) => {
   iso2.value = option.iso2
}
</script>
`
使用input,type为phone时，传了iso2,area_code默认值，没有显示默认区号，回显也是空的。下载源码调试也是这样。
![image](https://user-images.githubusercontent.com/66305157/223606191-ac2547e7-f938-4bfa-a50e-c8585cc6bd81.png)
![image](https://user-images.githubusercontent.com/66305157/223606242-7a978dcb-b986-47f8-98a4-dba300803854.png)

**Comment by 941477276** [comment]
我用你的代码运行了下并未出现你说的情况
![image](https://user-images.githubusercontent.com/20528541/223659484-8c9f82c9-0846-4c93-8c9f-10400236cffb.png)
![image](https://user-images.githubusercontent.com/20528541/223659826-b136b439-4817-432f-87c6-cea4b23b5839.png)

**Comment by shallow-time** [comment]
请问你是设置iso2，area_code默认值，默认自动显示的美国下拉项，还是手动选择的？我这边是不能默认显示

**Comment by 941477276** [comment]
没有手动选择，默认可以显示。
你的代码写的有问题
![image](https://user-images.githubusercontent.com/20528541/223954908-c90d1f6b-b1eb-4ffd-8def-e784625be46b.png)

**Comment by shallow-time** [comment]
我试了一下，之前我是使用yarn命令安装的，会导致以上问题，更换npm安装是没问题了
